spring:
  datasource:
    url: jdbc:mysql://localhost:3306/advanced?serverTimezone=UTC
    username: root
    password: poi1109~
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

jwt:
  secret:
    key: fb8e84eb4aab4827836f3199efc34499f4bf6c5374cc404c8851fd5de54de518de53